version: "3.9"

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["go", "run", "server.go"]

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5452:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
