version: "3.9"

services:
  app:
    build: .
    container_name: go-graphql-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment: .env
    volumes:
      - .:/app
    command: ["go", "run", "server.go"]

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
